[build]
  command = "npm install --production"
  publish = "."

[functions]
  directory = "functions"

[context.production.environment]
  NODE_ENV = "production"
  BASE_URL = "https://tax-free-period.netlify.app"
